version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_PASSWORD: '123456789qwerty'
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'productstore'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    networks:
      - app-network


#PHP Service
app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Docker Networks
networks:
  app-network:
    driver: bridge

